dist: trusty
sudo: false

language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~3.4.0"
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~4.1.0"
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="^4.2@dev"

matrix:
  include:
    -
      php: 7.1
      env: PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~3.4.0" DEPS="low"
    -
      php: 7.2
      env: RUN_PHPSTAN="yes"

branches:
  only:
    - master
    - /^\d.\d+-release$/

before_script:
  - phpenv config-rm xdebug.ini
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Read-only OAuth token to work around GitHub API rate limits
  - composer config -g github-oauth.github.com "4b3b0a83ea27d9544d3608a384c7a14625a98804"

  - if [ "$SYMFONY_VERSION" != "" ] ; then composer require --no-update symfony/symfony:$SYMFONY_VERSION ; fi

  - |
    if [ "$DEPS" = "low" ] ; then
      composer update --no-suggest --prefer-dist --prefer-lowest --prefer-stable
    else
      composer update --no-suggest --prefer-dist
    fi

script:
  - composer validate --strict
  - if [ "$PHPUNIT_CONFIG" != "" ] ; then vendor/bin/phpunit -c $PHPUNIT_CONFIG --colors=always ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan-tests ; fi

notifications:
  email: false
  slack:
    secure: s65kvb7bnQQHlg3afD0BRrhRxfhVUCTHqQUn3k4FPW15Dez65SXDKFCCkl4JQksblmKnhrTr82dOfP24DrD4WUllQr1Vdc7IPvXOC9jmge/bwA9LlTw9TH+xfShgi65UZlAfLxnywOwtKDuyzudNXA6QrFYiv7Z+bj7zjBRx+lAKlZWVFj2w2oxz3J94FzexUdZQh1wHEpouBGJvZpAd2w1Uj1453RGHvvs0RElEW1bBfw43CAstUSRAfdnZ7uWj0kGDFwwE3+e3PecOnAOIy6b47fY3AEBf3uy2r2zIBMBwLTmQ3v548zvGKGoXEvfIg7RhkwzcH/minQq6doiGOqZaV9TVCuxkYPawDdC32K2mqbOA1rPnE5exivcjRkXnzlhcBnG6HcaEm3+8VDw6lofLZ+yGd5i/nlyPBAAGAJn33tu+8qlPQbeUMglVqblfM6lbH4GIfzWNPJENrlN/IjIK4JSZxu2pR7evMSGggLfw2HScj3iUlbVtH2h6JK5f9H2+YZqNjGN8j8sO7JcIWWUnrc+yZmlAolzDB2pVuDccIM03xRULfoenWbgZVH3gXUsK7Yw5YR4B59vsTALA59letNFY3G46XbOsfaeAN3tEA4dl4UzjqPNhdovaprQOdYN1kC3+VbuIhPyvtXaVM5L7eHIfpEAkkRblmJR1yAg=
    on_success: change
    on_failure: always
    on_pull_requests: false

git:
  depth: 1
