services:
    netgen_layouts.sylius.event_listener.admin.main_menu_builder:
        class: Netgen\Bundle\LayoutsSyliusBundle\EventListener\Admin\MainMenuBuilderListener
        arguments:
            - "@security.authorization_checker"
        tags:
            - { name: kernel.event_subscriber }

    netgen_layouts.sylius.event_listener.admin.set_page_layout:
        class: Netgen\Bundle\LayoutsSyliusBundle\EventListener\Admin\SetPageLayoutListener
        arguments:
            - "%netgen_layouts.sylius.admin.pagelayout%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_layouts.sylius.event_listener.shop.product_show:
        class: Netgen\Bundle\LayoutsSyliusBundle\EventListener\Shop\ProductShowListener
        arguments:
            - "@request_stack"
            - "@netgen_block_manager.context"
        tags:
            - { name: kernel.event_subscriber }

    netgen_layouts.sylius.event_listener.shop.product_index:
        class: Netgen\Bundle\LayoutsSyliusBundle\EventListener\Shop\ProductIndexListener
        arguments:
            - "@sylius.repository.taxon"
            - "@sylius.context.locale"
            - "@request_stack"
            - "@netgen_block_manager.context"
        tags:
            - { name: kernel.event_subscriber }
