services:
    netgen_block_manager.sylius.event_listener.admin.main_menu_builder:
        class: Netgen\Bundle\SyliusBlockManagerBundle\EventListener\Admin\MainMenuBuilderListener
        arguments:
            - "@security.authorization_checker"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.sylius.event_listener.shop.product_show:
        class: Netgen\Bundle\SyliusBlockManagerBundle\EventListener\Shop\ProductShowListener
        arguments:
            - "@request_stack"
        tags:
            - { name: kernel.event_subscriber }
