services:
    netgen_block_manager.sylius.event_listener.admin.main_menu_builder:
        class: Netgen\Bundle\SyliusBlockManagerBundle\EventListener\Admin\MainMenuBuilderListener
        public: false
        arguments:
            - "@security.authorization_checker"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.sylius.event_listener.admin.set_page_layout:
        class: Netgen\Bundle\SyliusBlockManagerBundle\EventListener\Admin\SetPageLayoutListener
        public: false
        arguments:
            - "%netgen_block_manager.sylius.admin.pagelayout%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.sylius.event_listener.shop.product_show:
        class: Netgen\Bundle\SyliusBlockManagerBundle\EventListener\Shop\ProductShowListener
        public: false
        arguments:
            - "@request_stack"
            - "@netgen_block_manager.context"
        tags:
            - { name: kernel.event_subscriber }
