parameters:
    netgen_block_manager.item.value_converter.sylius_product.class: Netgen\BlockManager\Sylius\Item\ValueConverter\ProductValueConverter
    netgen_block_manager.item.value_loader.sylius_product.class: Netgen\BlockManager\Sylius\Item\ValueLoader\ProductValueLoader

services:
    netgen_block_manager.item.value_converter.sylius_product:
        class: "%netgen_block_manager.item.value_converter.sylius_product.class%"
        tags:
            - { name: netgen_block_manager.item.value_converter }

    netgen_block_manager.item.value_loader.sylius_product:
        class: "%netgen_block_manager.item.value_loader.sylius_product.class%"
        arguments:
            - "@sylius.repository.product"
        tags:
            - { name: netgen_block_manager.item.value_loader }
