services:
    netgen_layouts.sylius.item.value_converter.product:
        class: Netgen\Layouts\Sylius\Item\ValueConverter\ProductValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.item.value_loader.product:
        class: Netgen\Layouts\Sylius\Item\ValueLoader\ProductValueLoader
        arguments:
            - "@sylius.repository.product"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: sylius_product }

    netgen_layouts.sylius.item.value_url_generator.product:
        class: Netgen\Layouts\Sylius\Item\ValueUrlGenerator\ProductValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: sylius_product }

    netgen_layouts.sylius.item.value_converter.taxon:
        class: Netgen\Layouts\Sylius\Item\ValueConverter\TaxonValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.sylius.item.value_loader.taxon:
        class: Netgen\Layouts\Sylius\Item\ValueLoader\TaxonValueLoader
        arguments:
            - "@sylius.repository.taxon"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: sylius_taxon }
