services:
    netgen_block_manager.sylius.layout.resolver.target_type.product:
        class: Netgen\BlockManager\Sylius\Layout\Resolver\TargetType\Product
        tags:
            - { name: netgen_block_manager.layout.resolver.target_type, priority: 160 }

    netgen_block_manager.sylius.layout.resolver.form.target_type.mapper.product:
        class: Netgen\BlockManager\Sylius\Layout\Resolver\Form\TargetType\Mapper\Product
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: sylius_product }

    netgen_block_manager.sylius.persistence.doctrine.layout_resolver.query_handler.target_handler.sylius_product:
        class: Netgen\BlockManager\Sylius\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\Product
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, target_type: sylius_product }
