services:
    netgen_block_manager.locale.provider:
        alias: netgen_layouts.sylius.locale.provider
        public: false

    netgen_layouts.sylius.locale.provider:
        class: Netgen\Layouts\Sylius\Locale\LocaleProvider
        public: false
        arguments:
            - "@sylius.locale_provider"
