services:
    netgen_layouts.locale.provider:
        alias: netgen_layouts.sylius.locale.provider

    netgen_layouts.sylius.locale.provider:
        class: Netgen\Layouts\Sylius\Locale\LocaleProvider
        arguments:
            - "@sylius.locale_provider"
