services:
    netgen_layouts.sylius.parameters.parameter_type.taxon:
        class: Netgen\Layouts\Sylius\Parameters\ParameterType\TaxonType
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_layouts.sylius.parameters.form.mapper.taxon:
        class: Netgen\Layouts\Sylius\Parameters\Form\Mapper\TaxonMapper
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: sylius_taxon }
