services:
    netgen_block_manager.parameters.parameter_type.sylius_taxon:
        class: Netgen\BlockManager\Sylius\Parameters\ParameterType\TaxonType
        public: false
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.form.mapper.sylius_taxon:
        class: Netgen\BlockManager\Sylius\Parameters\Form\Mapper\TaxonMapper
        public: false
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: sylius_taxon }
