services:
    netgen_layouts.sylius.security.admin_access_voter:
        class: Netgen\Layouts\Sylius\Security\Authorization\Voter\AdminAccessVoter
        tags:
            - { name: security.voter }
