services:
    netgen_block_manager.sylius.templating.twig.extension.sylius:
        class: Netgen\Bundle\SyliusBlockManagerBundle\Templating\Twig\Extension\SyliusExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen_block_manager.sylius.templating.twig.runtime.sylius:
        class: Netgen\Bundle\SyliusBlockManagerBundle\Templating\Twig\Runtime\SyliusRuntime
        arguments:
            - "@sylius.repository.product"
            - "@sylius.repository.taxon"
        tags:
            - { name: twig.runtime }
            - { name: netgen_block_manager.twig.runtime }
