services:
    netgen_layouts.sylius.templating.twig.extension.sylius:
        class: Netgen\Bundle\LayoutsSyliusBundle\Templating\Twig\Extension\SyliusExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen_layouts.sylius.templating.twig.runtime.sylius:
        class: Netgen\Bundle\LayoutsSyliusBundle\Templating\Twig\Runtime\SyliusRuntime
        public: false
        arguments:
            - "@sylius.repository.product"
            - "@sylius.repository.taxon"
        tags:
            - { name: twig.runtime }
