services:
    netgen_layouts.sylius.validator.product:
        class: Netgen\Layouts\Sylius\Validator\ProductValidator
        public: false
        arguments:
            - "@sylius.repository.product"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_product }

    netgen_layouts.sylius.validator.taxon:
        class: Netgen\Layouts\Sylius\Validator\TaxonValidator
        public: false
        arguments:
            - "@sylius.repository.taxon"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_taxon }
