view:
    item_view:
        api:
            sylius_product:
                template: "@NetgenSyliusBlockManager/api/item/view/sylius_product.html.twig"
                match:
                    item\value_type: sylius_product
