view:
    item_view:
        default:
            sylius_product:
                template: "@nglayouts/item/sylius_product.html.twig"
                match:
                    item\value_type: sylius_product
        ajax:
            sylius_product:
                template: "@nglayouts/item/sylius_product.html.twig"
                match:
                    item\value_type: sylius_product
        app:
            sylius_product:
                template: "@nglayouts_admin/app/item/sylius_product.html.twig"
                match:
                    item\value_type: sylius_product
