view:
    item_view:
        default:
            sylius_product:
                template: "@NetgenSyliusBlockManager/item/view/sylius_product.html.twig"
                match:
                    item\value_type: sylius_product
        api:
            sylius_product:
                template: "@NetgenSyliusBlockManager/api/item/view/sylius_product.html.twig"
                match:
                    item\value_type: sylius_product
                    api_version: 1
