view:
    item_view:
        api:
            sylius_product:
                template: "NetgenSyliusBlockManagerBundle:api/item/view:sylius_product.html.twig"
                match:
                    item\value_type: sylius_product
