view:
    rule_target_view:
        value:
            sylius_product:
                template: "@NetgenLayoutsSylius/admin/layout_resolver/target/value/product.html.twig"
                match:
                    rule_target\type: sylius_product
            sylius_taxon:
                template: "@NetgenLayoutsSylius/admin/layout_resolver/target/value/taxon.html.twig"
                match:
                    rule_target\type: sylius_taxon
            sylius_taxon_product:
                template: "@NetgenLayoutsSylius/admin/layout_resolver/target/value/taxon_product.html.twig"
                match:
                    rule_target\type: sylius_taxon_product
